"""add unique constraint to reviews

Revision ID: 2c26bbe226a3
Revises: f2d3cc210e1f
Create Date: 2026-07-14 22:50:28.182888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c26bbe226a3'
down_revision = 'f2d3cc210e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_book_review', ['user_id', 'google_book_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_book_review', type_='unique')

    # ### end Alembic commands ###
