"""Make reviews.user_id nullable

Revision ID: 357c315fd49e
Revises: 2c26bbe226a3
Create Date: 2026-07-15 21:42:41.631554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357c315fd49e'
down_revision = '2c26bbe226a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
